name: Trigger Deploy
on:
  push:
    branches: [ main ]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository note-zk-quartz to deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/koei-kaji/note-zk-quartz/actions/workflows/deploy.yaml/dispatches \
            -d '{"ref":"v4"}'
